In [2]:
import torch

Broadcasting example </br>
Broadcasting: Broadcasting is a way to perform an operation between tensors that have similarities in their shapes. 

In [3]:
rand = torch.rand(2,4)
rand

tensor([[0.4166, 0.5932, 0.7087, 0.1638],
        [0.0541, 0.1819, 0.9067, 0.8734]])

In [5]:
ones = torch.ones(1, 4) * 2
ones

tensor([[2., 2., 2., 2.]])

In [7]:
double = rand * ones
double

tensor([[0.8332, 1.1864, 1.4173, 0.3276],
        [0.1082, 0.3639, 1.8134, 1.7467]])

In [8]:
a = torch.ones(4, 3, 2)
a

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [9]:
b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a

d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1


tensor([[[0.6463, 0.5482],
         [0.5720, 0.9831],
         [0.5353, 0.3189]],

        [[0.6463, 0.5482],
         [0.5720, 0.9831],
         [0.5353, 0.3189]],

        [[0.6463, 0.5482],
         [0.5720, 0.9831],
         [0.5353, 0.3189]],

        [[0.6463, 0.5482],
         [0.5720, 0.9831],
         [0.5353, 0.3189]]])
